wget https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.29/lolMiner_v1.29_Lin64.tar.gz
tar -xf lolMiner_v1.29_Lin64.tar.gz
cd 1.29
./lolMiner --algo ETHASH --pool ethash.unmineable.com:3333 --user ETH:0x2dEF8F795aB59CaF4D2c5485301FA63fA6539D63.developwithnitin --ethstratum ETHPROXY
